# Generated by Django 5.0.6 on 2024-06-27 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_activite', models.CharField(max_length=255)),
                ('categories', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CentreSportif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_centre', models.CharField(max_length=255)),
                ('prenom_centre', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=255)),
                ('prenom_client', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('age', models.IntegerField()),
                ('choix_sport', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Moniteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=255)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CentreSportif.activite')),
                ('moniteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CentreSportif.moniteur')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField()),
                ('statut_inscription', models.CharField(choices=[('en cours', 'En cours'), ('annulée', 'Annulée'), ('approuvée', 'Approuvée')], max_length=10)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CentreSportif.activite')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CentreSportif.client')),
                ('horaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CentreSportif.horaire')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('mode_paiement', models.CharField(max_length=255)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CentreSportif.inscription')),
            ],
        ),
    ]
