# Generated by Django 5.0.6 on 2024-06-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CentreSportif', '0002_remove_client_email_alter_client_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centresportif',
            name='prenom_centre',
        ),
    ]
