# Generated by Django 5.0.6 on 2024-06-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentreSportif', '0003_remove_centresportif_prenom_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centresportif',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
