# Generated by Django 5.0.6 on 2024-06-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CentreSportif', '0004_alter_centresportif_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CentreSportif',
        ),
    ]
