# Generated by Django 5.0.6 on 2024-06-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentreSportif', '0005_delete_centresportif'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='image',
            field=models.CharField(blank=True, max_length=20800, null=True),
        ),
    ]
