# Generated by Django 5.0.6 on 2024-06-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentreSportif', '0007_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='prix',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
