# Generated by Django 5.0.6 on 2024-06-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentreSportif', '0008_activite_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='image',
            field=models.ImageField(upload_to='./image'),
        ),
    ]
