# Generated by Django 5.0.6 on 2024-06-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentreSportif', '0009_alter_activite_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='image',
            field=models.CharField(max_length=2800),
        ),
    ]
