# Generated by Django 5.0.6 on 2024-06-28 20:12

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentreSportif', '0010_alter_activite_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=builtins.input, max_length=255),
            preserve_default=False,
        ),
    ]
