# Generated by Django 5.0.6 on 2024-07-03 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentreSportif', '0015_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date_inscription',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
