# Generated by Django 5.0.6 on 2024-07-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentreSportif', '0016_alter_inscription_date_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire',
            name='jour',
            field=models.CharField(max_length=10),
        ),
    ]
